### ISSUE TITLE
modals.record.edit.no-editable-fields.title     This note has no editable fields.

### ISSUE THREAD

**Issue by LJames123** [marcusolsson/obsidian-projects#55]
obsidian 0.16.5    modals.record.edit.no-editable-fields.title This note has no editable fields.

**Comment by marcusolsson** [comment]
Thank you! Fixed in 0.17.3.

**Comment by LJames123** [comment]
![image](https://user-images.githubusercontent.com/54067260/194900938-9cf55040-95fb-4386-ba42-50b5be275d7a.png)

**Comment by LJames123** [comment]
> Are you saying it still exists? What version of the plugin are you running?

Yes, project plugin 0.17.3, obsidian 0.16.5
When I click on ①, the prompt in ② pops up.
![image](https://user-images.githubusercontent.com/54067260/194907881-97d94808-1ccb-4235-9bb8-73cb6ef68808.png)

In addition, it would be perfect if there was an instruction manual.

**Comment by marcusolsson** [comment]
Oh, I see now that the latest release build didn't complete. 0.17.4 should fix this, once the build is done :)

**Comment by LJames123** [comment]
I updated to version 0.17.7 and I'm still having the same problem. Maybe I'm not using it the right way

**Comment by LJames123** [comment]
I updated to version 0.17.7 and I'm still having the same problem. Maybe I'm not using it the right way

**Comment by marcusolsson** [comment]
Wait. What's the actual issue you're referring to? 😅  I fixed the localization text, which I now see has been fixed in your screenshot.

Are you perhaps referring to the callout itself? Is your project perhaps using Dataview? There's currently no way of editing notes in a Dataview project, which is why you're seeing the callout.

One of the reasons is that I currently have no way of determining the original field name (without parsing the Dataview query myself). For example, if you run `TABLE stat AS "Status"`, the result will have a field called Status. But I'd need to know the original field name, `stat`, to actually update it.
